"""empty message

Revision ID: 47ec2397ab74
Revises: 
Create Date: 2022-01-04 17:14:14.857989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ec2397ab74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ka_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(), nullable=False),
    sa.Column('seasons', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.Column('released_date', sa.DateTime(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ka_series')
    # ### end Alembic commands ###
